#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

CONTAINER_REGISTRY="ghcr.io"
SELF="$(readlink -f "$0")"
if [ "$SELF" == */vendor/*/wiring/ops ]; then
    SELFDIR="$(dirname "$SELF")"
    DIR="$(dirname "$(dirname "$(dirname "$SELFDIR")")")"
else
    SELFDIR="$(dirname "$SELF")"
    DIR="$SELFDIR"
fi
BASE="$(dirname "$(dirname "$DIR")")"
ACCOUNT="$(basename "$(dirname "$DIR")")"
PROJECT="$(basename "$DIR")"
ID="$CONTAINER_REGISTRY/$ACCOUNT/$PROJECT"

cd "$DIR"

function volumes() {
    VOLUMES=()
    for volume in "$@"
    do
        case "$volume" in
            src)
                VOLUMES+=("-v" "./src:/app/src:ro")
                ;;
            test)
                mkdir -p "./tests"
                VOLUMES+=("-v" "./tests:/app/tests:ro")
                ;;
            phpunit)
                VOLUMES+=("-v" "./phpunit.xml:/app/phpunit.xml:ro")
                ;;
            coverage)
                mkdir -p "./docs/coverage"
                VOLUMES+=("-v" "./docs/coverage:/app/docs/coverage:rw")
                ;;
            dependencies)
                for DEPENDENCY in `sed -n '/"require": {/,/}/p' composer.json | grep '^ *"[a-z-]*/[a-z-]*":' | grep -o '[a-z-]*/[a-z-]*'`
                do
                    if [ -d "$BASE/$DEPENDENCY/src" ]; then
                        VOLUMES+=("-v" "$BASE/$DEPENDENCY/src:/app/vendor/$DEPENDENCY/src:ro")
                    fi
                done
                ;;
        esac
    done
}

case "${1:-}" in
    login)
        podman login "$CONTAINER_REGISTRY"
        ;;

    build)
        if [ ! -f "composer.lock" ]
        then
            exec "$SELF" update
        fi

        case "${2:-dev}" in
            dev)
                buildah bud -t "$ID:dev" "dev.containerfile"
                ;;

            *)
                buildah bud -t "$ID:${2:-latest}" "release.containerfile"
                ;;
        esac
        ;;

    base)
        case "${2:-}" in
            build)
                buildah bud -t "$ID:base-dev" "$SELFDIR/base-dev.containerfile"
                buildah bud -t "$ID:base-release" "$SELFDIR/base-release.containerfile"
                ;;

            publish)
                podman push "$ID:base-dev"
                podman push "$ID:base-release"
                ;;
        esac
        ;;

    update | require)
        CMD="$1"
        shift
        podman run -it --rm -v ./:/app/ composer composer "$CMD" --no-install $*
        exec "$SELF" build
        ;;

    publish)
        podman push "$ID:${2:-latest}"
        ;;

    test)
        volumes src test phpunit coverage dependencies
        shift
        podman run -it --rm "${VOLUMES[@]}" "$ID:dev" \
            php /app/vendor/bin/phpunit --coverage-html /app/docs/coverage /app/tests $*
        ;;

    check)
        volumes src test
        podman run -it --rm "${VOLUMES[@]}" "$ID:dev" \
            find src tests -name "*.php" -type f -exec php -l "{}" \;
        ;;

    bash)
        volumes src test
        podman run -it --rm "${VOLUMES[@]}" "$ID:${2:-dev}" bash
        ;;

    run-*)
        TAG="${1:4}"
        if [ "$TAG" == "dev" ]; then
            volumes src dependencies
        fi
        shift
        podman run -it --rm "${VOLUMES[@]}" "$ID:$TAG" $*
        ;;

    run)
        shift
        podman run -it --rm "$ID:latest" $*
        ;;

    status | add | commit | pull | push | stash | diff)
        git $*
        ;;

    "")
        echo "Usage: $0 ( login | build | update | require | publish | test | run | check | bash | status | add | commit | pull | push | stash | diff)"
        ;;

    *)
        echo "No such subcommand: $@"
        ;;
esac
